### ISSUE TITLE
Where to find main class in Java files

### ISSUE THREAD

**Issue by edanian** [wakaleo/game-of-life#36]
Hi,

I would like to know where the definition of the main class is done i the example project game-of-life?

Any help would be appreciated.

BR Daniel

**Comment by alex-87** [comment]
Hello,

  This is J2EE, so there is no "public static void main(...)" like a JSE software. ButI found the Controller class here https://github.com/wakaleo/game-of-life/blob/master/gameoflife-web/src/main/java/com/wakaleo/gameoflife/webtests/controllers/GameController.java and could be considered as the "main class" for J2EE.

  I hope answered well (sorry for my english).

Best regards.

**Comment by edanian** [comment]
Hi Alex,

Thanks a lot for your helpful explanation.
If I would like to build the game-of-life in e.g. Eclipse, can I then download Java EE SDK and try it out?

Do you also happen to know where the Maven build files can be found on a Windows PC? In Jenkins it just says: Default (~/.m2/repository)

BR Daniel

**Comment by alex-87** [comment]
If you want to build the game-of-life with Eclipse Java EE SDK, you will need a Servlet Container (like Tomcat) to load the software. The paradigm of J2EE is to provide a platform for web applications, like this one. Eclipse with the Java EE SDK handles the Servlet Container (start, run, debug, pause, stop the software).

For Maven under Microsoft Windows, I really don't know how about it, sorry :(

BR,
Alex.

**Comment by edanian** [comment]
Ok, thanks a lot for your help!

**Comment by JavierPeris** [comment]
It has been a long time and I am surprised that this issue is still open. If your question is the location of the local Maven cache in Windows is like in GNU/Linux, that is, it is under your user home (in Windows you can go there typing %userprofile%\.m2\repository)

**Comment by wakaleo** [comment]
I think we can consider this question answered - since this is a J2EE app, there is no "main" class as such.
